### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by facorazza** [xwavex/Ingress-Version-Extractor#1]
I followed the instruction but couldn't make it work:
`java.lang.NoClassDefFoundError: de/dlw/ingress/version/extractor/main/IVEMain (wrong name: IVEMain)`

**Comment by xwavex** [comment]
If you want to compile the tool on the command line, just include the src folder to the classpath:
```bash
$ git clone https://github.com/xwavex/Ingress-Version-Extractor.git
$ cd Ingress-Version-Extractor/src/
# compile with javac
$ javac -cp . de/dlw/ingress/version/extractor/main/IVEMain.java
# run with java
$ java -cp . de/dlw/ingress/version/extractor/main/IVEMain     
Parameters do NOT match. Have to be == 2


Usage: IngressVersionExtractor <apkFilePath> <releaseDate>

        Example:
                <apkFilePath>   res/ingress_version_1.33.apk
                <releaseDate>   2013-08


by Dennis Leroy Wigand
```

However, I assume that this code might be outdated, since my last changes date back 4 years.
Feel free to modify the code as you need it.
